services:
  - type: web
    name: pazhampori-backend
    env: node
    region: singapore
    plan: free
    buildCommand: cd Backend && npm install
    startCommand: cd Backend && npm start
    envVars:
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production